## Introduction, Motivation and/or Problem Statement

## Data Sources or RL Tasks

## Exploratory Analysis of Data or RL Tasks

## Models and/or Methods

### Baseline Model Comparison
| Model | Accuracy | Macro F1 | ROC AUC(OvR) | Best Class | Worst Class |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
| TF-IDF + Logistic Regression | 24.8% | 0.226 | 0.604 | false | pants-fire|
| LSTM + Random Embedding | 24% | 0.230 | 0.563 | false | pants-fire |
| BERT Network | 25.65% | 0.2389 | 0.6106 | false | true |

As is shown above, Bert network has the best performance among the three models. Consequently, we will use Bert network as our final baseline model.

**Using BERT as the baseline, we made the following improvements:**

| Origin Model | Improvement 1 | Improvement 2 | Improvement 3 | Improvement 4 |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| Accuracy | 25.65% | 33.15% | 34.41% | 36.07% | 37.33% |
| Macro F1 | 0.2389 | 0.2587 | 0.3178 | 0.3315 | 0.3311 |

- **Improvement 1: Dual-Branch BERT Architecture:**
Designed a two-branch BERT model that processes both the statement and metadata inputs independently through separate BERT encoders. Their outputs are concatenated and enhanced by integrating a credit-based feature vector before classification, allowing the model to incorporate contextual credibility information.

- **Improvement 2: Asymmetric Loss Function (ASL):**
Employed the Asymmetric Loss function, which effectively handles class imbalance by penalizing false negatives more than false positives—especially useful for skewed label distributions in fake news detection.

- **Improvement 3: Virtual Adversarial Training (VAT):**
Integrated Virtual Adversarial Training to improve model robustness. VAT encourages the model to produce stable predictions under small perturbations, enhancing generalization and defense against adversarial examples.

- **Improvement 4: Regularized Dropout (R-Drop):**
Applied Regularized Dropout (R-Drop) by enforcing consistency between two stochastic forward passes, which helps reduce overfitting and aligns model predictions during training.

In [ ]:
!python bert_origin.py

cuda:0
starting
Epoch 1/100
----------
train total loss: 1.7727
train sentiment_acc: 0.2109

 Classification Report:
              precision    recall  f1-score   support

           0     0.1794    0.1205    0.1442      1676
           1     0.2128    0.2732    0.2392      1962
           2     0.2103    0.3198    0.2537      2114
           3     0.2069    0.1421    0.1685      1654
           4     0.2274    0.2546    0.2402      1995
           5     0.3000    0.0036    0.0071       839

    accuracy                         0.2109     10240
   macro avg     0.2228    0.1856    0.1755     10240
weighted avg     0.2158    0.2109    0.1964     10240


 Confusion Matrix:
[[202 443 520 154 357   0]
 [225 536 651 186 363   1]
 [224 509 676 239 465   1]
 [180 391 518 235 328   2]
 [219 451 600 214 508   3]
 [ 76 189 250 108 213   3]]
val total loss: 1.7263
val sentiment_acc: 0.2430

 Classification Report:
/root/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:15

## Results

In [11]:
!python bert_network_with_VAT_RDrop.py

cuda:0
{'train': <torch.utils.data.dataloader.DataLoader object at 0x7f58241d9130>, 'val': <torch.utils.data.dataloader.DataLoader object at 0x7f582412fd70>, 'test': <torch.utils.data.dataloader.DataLoader object at 0x7f5823923c80>}
{'train': 10240, 'val': 1284, 'test': 1267}
starting
Epoch 1/100
----------
train total loss: 1.2699
train sentiment_acc: 0.2754

 Classification Report:
              precision    recall  f1-score   support

           0     0.2338    0.1014    0.1415      1676
           1     0.3389    0.3818    0.3591      1962
           2     0.2555    0.3543    0.2969      2114
           3     0.2060    0.1282    0.1580      1654
           4     0.2664    0.4100    0.3230      1995
           5     0.4469    0.1454    0.2194       839

    accuracy                         0.2754     10240
   macro avg     0.2913    0.2535    0.2497     10240
weighted avg     0.2778    0.2754    0.2597     10240


 Confusion Matrix:
[[170 443 557 123 370  13]
 [185 749 581  96 343  

## Discussion

## Writing